// Generated by CoffeeScript 1.8.0
(function() {
  var JSONs, PASHALIST;

  PASHALIST = window.PASHALIST = window.PASHALIST || {};

  JSONs = (function() {
    function JSONs() {}

    JSONs.sponsorship = 'json/sponsorships.json';

    JSONs.onlineshopitem = 'json/onlineshopitems.json';

    JSONs.pashalist = 'json/pashalists.json';

    JSONs.top5pashalist = 'json/top5pashalists.json';

    JSONs.freePhoto = 'json/freephotos.json';

    JSONs.featured = 'json/featureds.json';

    return JSONs;

  })();

  window.PASHALIST.JSONs = JSONs;

}).call(this);
