document.write(
'<script src="j/jquery-1.11.1.min.js"></script>'
+'<script src="j/underscore-min.js"></script>'
+'<script src="j/underscore.string.min.js"></script>'
+'<script src="j/_.js"></script>'
+'<script src="j/jquery.bxslider.min.js"></script>'
+'<script src="j/jquery.ellipsis.min.js"></script>'
+'<script src="j/jquery.localscroll.js"></script>'
+'<script src="j/jquery.maximage.min.js"></script>'
+'<script src="j/jquery.scrollTo.min.js"></script>'
+'<script src="j/jquery.slides.min.js"></script>'
+'<script src="j/jquery.smarttruncation.js"></script>'
+'<script src="j/backbone-min.js"></script>'
+'<script src="j/bootstrap.min.js"></script>'
+'<script src="j/coffee-script.js"></script>'
+'<script src="j/createjs-2013.12.12.min.js"></script>'
+'<script src="j/imgLiquid-min.js"></script>'
+'<script src="j/masonry.pkgd.min.js"></script>'
+'<script src="j/paper-full.min.js"></script>'
+'<script src="j/tabulous.min.js"></script>'
+'<script src="j/trunk8.min.js"></script>'
+'<script src="j/jquery.smoothScroll.js"></script>'
+'<script src="j/modernizr.custom.62033.js"></script>'
+'<script src="co/templates.coffee" type="text/coffeescript"></script>'
+'<script src="co/jsons.coffee" type="text/coffeescript"></script>'
+'<script src="co/main.coffee" type="text/coffeescript"></script>'
);
